### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by constantlb** [mdmoin7/angular-sort-orderby-pipe#4]
npm WARN ngp-sort-pipe@0.0.4 requires a peer of @angular/common@^9.0.6 but none is installed. You must install peer dependencies yourself.

**Comment by mdmoin7** [comment]
I would recommend you to create the pipe, instead of using the library. As i would like one to create the pipe than use a library as it provides you with flexibility to modify as per your requirement. A blog has been written for the same on medium. 
https://mdmoin07.medium.com/sort-pipe-in-angular-6-7-f22475cc4054
